<a href="https://colab.research.google.com/github/Yasser282/python-Y/blob/main/4_save_and_load_model_using_pickle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h2 style="color:green" align="center">Machine Learning With Python: Save And Load Trained Model</h2>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/DSomair/Masar_DS/main/Datasets/Week%233/Area_Price.csv")
df.head()

Area   Price
0  2218  6056.8
1  3635  9443.0
2  2193  5463.8
3  2931  7743.6
4  3596  9075.6

In [ ]:
model = linear_model.LinearRegression()
model.fit(df[['Area']],df.Price)

LinearRegression()

In [ ]:
model.coef_

array([2.53413086])

In [ ]:
model.intercept_

135.38769776712525

In [ ]:
model.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([12806.04201906])

<h3 style='color:purple'>Save Model To a File Using Python Pickle</h3>

In [ ]:
import pickle

In [ ]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

<h4 style='color:purple'>Load Saved Model</h4>

In [ ]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [ ]:
mp.coef_

array([2.53413086])

In [ ]:
mp.intercept_

135.38769776712525

In [ ]:
mp.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([12806.04201906])